ALTER TABLE "prefecture_visits" DROP CONSTRAINT "prefecture_visits_pkey";--> statement-breakpoint
ALTER TABLE "prefecture_visits" DROP COLUMN "id";--> statement-breakpoint
ALTER TABLE "prefecture_visits" ADD COLUMN "id" bigint GENERATED BY DEFAULT AS IDENTITY;--> statement-breakpoint
UPDATE "prefecture_visits" SET "id" = DEFAULT WHERE "id" IS NULL;--> statement-breakpoint
ALTER TABLE "prefecture_visits" ALTER COLUMN "id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "prefecture_visits" ADD PRIMARY KEY ("id");--> statement-breakpoint
ALTER TABLE "prefecture_visits" DROP COLUMN "prefecture_name";
